# Generated by Django 5.1.7 on 2025-04-03 09:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('category', models.CharField(choices=[('electronics', 'ELECTRONICS'), ('clothes', 'CLOTHES'), ('footwear', 'FOOTWEAR'), ('food', 'FOOD'), ('general', 'GENERAL')], default='general', max_length=30)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
