# Generated by Django 5.1.7 on 2025-04-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=10)),
                ('president', models.CharField(blank=True, max_length=10, null=True)),
                ('population', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=5)),
                ('no_of_states', models.IntegerField(default=0)),
            ],
        ),
    ]
